default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  host: localhost
  database: wedding_development

test:
  <<: *default
  database: wedding_test

production:
  <<: *default
  url: "postgres://postgres:postgres@localhost/wedding_production"
  database: wedding_production
